### ISSUE TITLE
azsk-nunit-task' (1.0.0) is using deprecated task execution handler

### ISSUE THREAD

**Issue by mikanyg** [almmechanics/AzskUtils#3]
**Describe the bug**
Using the task azsk-nunit-task@1 outputs a warning in the build logs.

**To Reproduce**
Added the following step to a yaml build pipeline:
- task: azsk-nunit-task@1
  displayName: 'Convert AzSK to NUnit output'
  inputs:
    OutputVariable: 'AZSK.NUnit.OutputPath'

Build logs output:
##[warning]Task 'azsk-nunit-task' (1.0.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Expected behavior**
No warnings when using the task.

**Comment by almmechanics** [comment]
Agreed - im now looking to move this Azure DevOps task over to `Powershell3` format. This will pick up the new tasklib.

**Comment by almmechanics** [comment]
If you are using pester 5 (interface 3 in azure devops) then this  issue has been addressed
